### ISSUE TITLE
Leading zeros incorrectly allowed in pre-release identifiers

### ISSUE THREAD

**Issue by Coder-256** [steveklabnik/semver#220] opened 2020-11-08 23:35 UTC
Per [the spec](https://semver.org/#spec-item-9):

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes.

It's worded strangely but this actually means that any alphanumeric identifier must contain at least one non-digit, and any numeric number must not start with a zero (this restriction does not apply to the build identifiers). Some relevant parts of the grammar are:

```
<pre-release identifier> ::= <alphanumeric identifier>
                           | <numeric identifier>

<build identifier> ::= <alphanumeric identifier>
                     | <digits>

<alphanumeric identifier> ::= <non-digit>
                            | <non-digit> <identifier characters>
                            | <identifier characters> <non-digit>
                            | <identifier characters> <non-digit> <identifier characters>

<numeric identifier> ::= "0"
                       | <positive digit>
                       | <positive digit> <digits>
```

In fact, one of the invalid semantic versions from the test cases linked from [the FAQ](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string) is `1.2.3-0123`. It seems the problem is that [the parser simply considers any identifier beginning with a zero to be a valid alphanumeric identifier](https://github.com/steveklabnik/semver-parser/blob/v0.10.0/src/lexer.rs#L192-L196). However, from the grammar above, it is clear that this is not the case.

Probably the best way to fix this is just to verify that all alphanumeric sub-identifiers in the pre-release identifier contain at least one non-digit. However if this actually breaks things, I understand if it might be better to leave things as-is.

**Comment by dtolnay** [comment] 2020-11-26 06:15
Duplicate of #206&ensp;*"Parses invalid versions with leading \`0\` in numeric prerelease identifiers"*

**Closed** 2020-11-29 02:47 UTC
